### ISSUE TITLE
The `Session::reset` throws an exception when main window has name

### ISSUE THREAD

**Issue by aik099** [minkphp/webdriver-classic-driver#26]
When the main window has a name and a couple of other windows are open, then the `Session::reset` call throws a `NoSuchWindow` exception, because it tries to determine the main window handle by its name after a popup window was just deleted while Selenium is in context of that deleted window (Web View).

Maybe for the internal window manipulations, the driver should use only window handles.

Related issue: #25

P.S.
I stumbled upon this error after fixing the #25 problem locally.

**Comment by stof** [comment]
For internal usages, it would make sense to work directly with handles.

**Comment by aik099** [comment]
> For internal usages, it would make sense to work directly with handles.

Updated PR account to account for this.

**Comment by uuf6429** [comment]
> Maybe for the internal window manipulations, the driver should use only window handles.

Agreed, not sure why it wasn't like that already. We need to make sure that in old selenium we can also get some sort of window handle.

**Comment by aik099** [comment]
> ... We need to make sure that in old selenium we can also get some sort of window handle.

@uuf6429 , Tested on Selenium 2 and everything works.
