### ISSUE TITLE
Add default capabilities for a Firefox

### ISSUE THREAD

**Issue by aik099** [minkphp/webdriver-classic-driver#7]
I saw these Chrome default capabilities:

https://github.com/minkphp/webdriver-classic-driver/blob/3a116f9a7369412bb210ce4ad272288b42d05356/src/WebdriverClassicDriver.php#L44-L49

Is it possible to add similar ones for the Firefox browser?

**Comment by uuf6429** [comment]
Note that these default capabilities are just to tweak the browser to behave as normally/standard as possible.

I looked into this, but it doesn't seem that Firefox displays an automation notification bar. Let me know if there is something in particular that should be fixed/changed!

**Comment by aik099** [comment]
I test too much in Chrome now. I had forgotten, that Firefox has a nice robot FavIcon and no banner to indicate it's being controlled from the outside.

Sorry for the false report.

Thank you.
